### ISSUE TITLE
add OPERATOR_YAML variable in the makefile

### ISSUE THREAD

**Issue by mmalvezz** [gotsysdba/oracle-ords-operator#36]
**Describe the bug**
Missing variable OPERATOR_YAML in the makefile. Operator yaml file not generated during target operator-yaml execution 
```
325 OPERATOR_YAML=$$(basename $$(pwd)).yaml <-- add this line  
326 operator-yaml: manifests kustomize
327         cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
328          $(KUSTOMIZE) build config/default > "$(OPERATOR_YAML)"
329          sed -i.bak -e '/^apiVersion: apps\/v1/,/---/d' "$(OPERATOR_YAML)"
330         (echo --- && sed '/^apiVersion: apps\/v1/,/---/!d' "$(OPERATOR_YAML).bak")  >>  "$(OPERATOR_YAML)"
```
thx and ciao 
   Matteo

**Comment by gotsysdba** [comment]
Hi Matteo,
This is currently handled by `release-manifest` and is called as part of the `build-release` pipeline workflow.  The operator yaml is only an artifact to the release itself and not included in the main branch code-line to ensure only the tested/released manifests are used.

For dev, `make deploy` should be sufficient.  I can variable-ise OPERATOR_YAML, as it is currently hardcoded to `oracle-ords-operator.yaml`; but I may be misunderstanding your underlying requirement.
